spring.application.name=SherlockTest

spring.datasource.url=jdbc:h2:mem:sherlock-test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=testing
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop