spring.application.name=SherlockDefault

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/{vendor}

sherlock.webmaster.institution=DCS-Sherlock
sherlock.webmaster.contact=the webmaster
sherlock.webmaster.link=https://github.com/DCS-Sherlock/

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
server.tomcat.max-part-count=1000
server.tomcat.max-parameter-count=10000
