CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE TABLE IF NOT EXISTS PUBLIC.ACCOUNT (
    ID       BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL    VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255),
    NAME     VARCHAR(255),
    PRIMARY KEY (ID),
    UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS PUBLIC.DETECTOR (
    ID       BIGINT NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(255),
    TEMPLATE BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.PARAMETER (
    ID             BIGINT NOT NULL AUTO_INCREMENT,
    NAME           VARCHAR(255),
    PARAM_VALUE    DOUBLE,
    POSTPROCESSING BOOLEAN,
    T_DETECTOR     BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.ROLE (
    ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255),
    ACCOUNT BIGINT,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.TEMPLATE (
    ID        BIGINT NOT NULL AUTO_INCREMENT,
    IS_PUBLIC BOOLEAN,
    LANGUAGE  VARCHAR(255),
    NAME      VARCHAR(255),
    ACCOUNT   BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.WORKSPACE (
    ID        BIGINT NOT NULL AUTO_INCREMENT,
    ENGINE_ID BIGINT,
    ACCOUNT   BIGINT,
    PRIMARY KEY (ID)
);


ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT ROLE_REF_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES PUBLIC.ACCOUNT (ID);
ALTER TABLE PUBLIC.DETECTOR ADD CONSTRAINT DETECTOR_REF_TEMPLATE FOREIGN KEY (TEMPLATE) REFERENCES PUBLIC.TEMPLATE (ID);
ALTER TABLE PUBLIC.PARAMETER ADD CONSTRAINT PARAMETER_REF_DETECTOR FOREIGN KEY (T_DETECTOR) REFERENCES PUBLIC.DETECTOR (ID);
ALTER TABLE PUBLIC.TEMPLATE ADD CONSTRAINT TEMPLATE_REF_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES PUBLIC.ACCOUNT (ID);
ALTER TABLE PUBLIC.WORKSPACE ADD CONSTRAINT WORKSPACE_REF_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES PUBLIC.ACCOUNT (ID);
